# Generated by Django 5.1.3 on 2025-08-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_produit_prix_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresselivraison',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='adresselivraison',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
