# Generated by Django 5.1.3 on 2025-09-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_alter_panier_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('carte', 'Carte bancaire'), ('cinetpay', 'CinetPay'), ('whatsapp', 'Orange Money via WhatsApp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_promo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
